const state = {
  all: [], currentView: 'pendientesView', mediaRecorder: null, audioBlob: null, chunks: [], recognition: null,
  editorId: null, options: { actividades: [], conceptos: [] }, editorItem: null,
  createFiles: [], editorQueuedFiles: []
};
const els = {
  searchInput: document.getElementById('searchInput'), refreshBtn: document.getElementById('refreshBtn'), clearClosedBtn: document.getElementById('clearClosedBtn'),
  pendientesList: document.getElementById('pendientesList'), hechosList: document.getElementById('hechosList'), countPendientes: document.getElementById('countPendientes'), countHechos: document.getElementById('countHechos'),
  createForm: document.getElementById('createForm'), transcript: document.getElementById('transcript'), startRecording: document.getElementById('startRecording'), stopRecording: document.getElementById('stopRecording'), recordingStatus: document.getElementById('recordingStatus'), audioPreview: document.getElementById('audioPreview'), toast: document.getElementById('toast'),
  surfaceInput: document.getElementById('surfaceInput'), contentInput: document.getElementById('contentInput'), continenteInput: document.getElementById('continenteInput'), contentCause: document.getElementById('contentCause'), continentCalc: document.getElementById('continentCalc'), continentCause: document.getElementById('continentCause'), actividadSelect: document.getElementById('actividadSelect'), conceptosSelect: document.getElementById('conceptosSelect'),
  photoInput: document.getElementById('photoInput'), photoPreview: document.getElementById('photoPreview'),
  editorDialog: document.getElementById('editorDialog'), closeEditor: document.getElementById('closeEditor'), editorTitle: document.getElementById('editorTitle'), editorAudio: document.getElementById('editorAudio'), editorTranscript: document.getElementById('editorTranscript'), editorFields: document.getElementById('editorFields'), autofillBtn: document.getElementById('autofillBtn'), saveEditorBtn: document.getElementById('saveEditorBtn'), downloadReportBtn: document.getElementById('downloadReportBtn'), downloadPhotosBtn: document.getElementById('downloadPhotosBtn'), editorPhotoInput: document.getElementById('editorPhotoInput'), editorPhotoPreview: document.getElementById('editorPhotoPreview'), uploadEditorPhotosBtn: document.getElementById('uploadEditorPhotosBtn'), editorPhotoStatus: document.getElementById('editorPhotoStatus')
};
const editorConfig = [
  ['numeroSiniestro', 'Nº expediente'], ['numeroPoliza', 'Nº póliza'], ['ramo', 'Ramo'], ['modalidad', 'Modalidad'], ['situacionRiesgo', 'Situación riesgo', 'full'], ['asegurado', 'Asegurado'], ['fechaSiniestro', 'Fecha siniestro'],
  ['tipoSiniestro', 'Tipo siniestro'], ['causaSiniestro', 'Causa siniestro'], ['actividadRiesgo', 'Actividad'], ['regimen', 'Régimen'], ['tipoRiesgo', 'Tipo riesgo'], ['uso', 'Uso'], ['superficieConstruida', 'Superficie construida (m²)'],
  ['garajeMetros', 'Garaje / comunes (m²)'], ['muroVallas', 'Muro y vallas (ml)'], ['localizacion', 'Localización'], ['anoConstruccion', 'Año construcción'], ['materialesCombustibles', 'Materiales combustibles'], ['protecciones', 'Protecciones', 'textarea'],
  ['otrasCircunstancias', 'Otras circunstancias / informe pericial', 'textareaFull'], ['contenidoSuma', 'Contenido'], ['continenteSuma', 'Continente'], ['propuesta', 'Propuesta'], ['tipoRol', 'Tipo de rol'], ['actividad', 'Actividad'], ['conceptos', 'Conceptos'], ['codigos', 'Códigos'], ['observacionesBreves', 'Observaciones breves', 'textareaFull']
];
function showToast(message) { els.toast.textContent = message; els.toast.classList.remove('hidden'); setTimeout(() => els.toast.classList.add('hidden'), 2600); }
function money(value) { const n = Number(value || 0); return n.toLocaleString('es-ES', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + ' €'; }
function parseNumber(value) { if (!value) return 0; const str = String(value).replace(/€/g, '').replace(/\./g, '').replace(/,/g, '.').trim(); const num = Number(str); return Number.isFinite(num) ? num : 0; }
function continentData(surface, insured) { const metros = parseNumber(surface); const suma = parseNumber(insured); const calc = metros * 950; let cause = 'NO CONSTA EN LA NOTA DEL PERITO'; if (metros && suma) { const ratio = Math.abs(calc - suma) / Math.max(suma, 1); if (ratio <= 0.08) cause = 'A valor real'; else if (calc > suma) cause = 'Infraseguro'; else cause = 'Sobreseguro'; } return { calc, cause }; }
function updateCreateCalc() { els.contentCause.textContent = 'A valor real'; const { calc, cause } = continentData(els.surfaceInput.value, els.continenteInput.value); els.continentCalc.textContent = money(calc); els.continentCause.textContent = cause; }
function switchView(viewId) { state.currentView = viewId; document.querySelectorAll('.view').forEach(el => el.classList.toggle('active-view', el.id === viewId)); document.querySelectorAll('.nav-btn').forEach(btn => btn.classList.toggle('active', btn.dataset.viewTarget === viewId)); }
async function api(path, options = {}) { const response = await fetch(path, options); if (!response.ok) { let message = 'Error'; try { const data = await response.json(); message = data.error || message; } catch { const text = await response.text(); if (text) message = text; } throw new Error(message); } const type = response.headers.get('content-type') || ''; if (type.includes('application/json')) return response.json(); return response.blob(); }
async function loadOptions() { const data = await api('/api/options'); state.options = data; for (const item of data.actividades) { const option = document.createElement('option'); option.value = item; option.textContent = item; els.actividadSelect.appendChild(option); } for (const item of data.conceptos) { const option = document.createElement('option'); option.value = item; option.textContent = item; els.conceptosSelect.appendChild(option); } }
function filteredCases() { const q = els.searchInput.value.trim().toLowerCase(); if (!q) return state.all; return state.all.filter(item => [item.numeroSiniestro, item.numeroPoliza, item.asegurado, item.situacionRiesgo, item.transcript, item.otrasCircunstancias].filter(Boolean).some(val => String(val).toLowerCase().includes(q))); }
function caseImages(item) { return (item.archivos || item.fotos || []).filter(f => (f.kind || '').toLowerCase() === 'image' || /\.(jpg|jpeg|png|webp|heic)$/i.test(f.name || '')); }
function photoStrip(item) { const fotos = caseImages(item); if (!fotos.length) return '<p class="muted small">Sin fotos</p>'; return `<div class="inline-photos">${fotos.slice(0,4).map(f => `<img src="${f.url}" alt="Foto">`).join('')}${fotos.length > 4 ? `<span class="photo-count">+${fotos.length - 4}</span>` : ''}</div>`; }
function cardTemplate(item, isDone = false) { const audio = item.audioUrl ? `<audio controls src="${item.audioUrl}"></audio>` : '<p class="muted">Sin audio adjunto</p>'; const totalFiles = (item.archivos || item.fotos || []).length; return `<article class="case-card"><div class="case-top"><div><p class="mini">Expediente</p><h3>${item.numeroSiniestro || 'Sin número'}</h3></div><span class="state-badge ${isDone ? 'done' : 'pending'}">${isDone ? 'Hecho' : 'Pendiente'}</span></div><div class="case-meta"><div><span>Póliza</span><strong>${item.numeroPoliza || '—'}</strong></div><div><span>Asegurado</span><strong>${item.asegurado || '—'}</strong></div><div><span>Dirección</span><strong>${item.situacionRiesgo || '—'}</strong></div></div><div class="audio-box">${audio}</div>${photoStrip(item)}<p class="muted small">Archivos adjuntos: ${totalFiles}</p><div class="card-actions"><button class="btn secondary" data-action="open" data-id="${item.id}">Abrir</button><button class="btn secondary" data-action="report" data-id="${item.id}">Descargar informe</button><button class="btn secondary" data-action="files" data-id="${item.id}">Descargar archivos</button><button class="btn secondary" data-action="toggle" data-id="${item.id}" data-next="${isDone ? 'Pendiente' : 'Hecho'}">${isDone ? 'Reabrir' : 'Hecho / cerrar'}</button><button class="btn danger" data-action="delete" data-id="${item.id}">Borrar</button></div></article>`; }
function renderLists() { const data = filteredCases(); const pendientes = data.filter(x => x.estado !== 'Hecho'); const hechos = data.filter(x => x.estado === 'Hecho'); els.countPendientes.textContent = `${pendientes.length} pendientes`; els.countHechos.textContent = `${hechos.length} hechos`; els.pendientesList.innerHTML = pendientes.length ? pendientes.map(x => cardTemplate(x, false)).join('') : '<div class="empty-card">No hay siniestros pendientes.</div>'; els.hechosList.innerHTML = hechos.length ? hechos.map(x => cardTemplate(x, true)).join('') : '<div class="empty-card">No hay siniestros hechos.</div>'; }
async function loadCases() { state.all = await api('/api/siniestros'); renderLists(); }
function buildEditorFields(item) { els.editorFields.innerHTML = editorConfig.map(([key, label, type]) => { const val = String(item[key] || '').replaceAll('"', '&quot;'); if (type === 'textarea') return `<div class="field"><label>${label}</label><textarea class="input textarea editor-input" data-key="${key}">${item[key] || ''}</textarea></div>`; if (type === 'textareaFull') return `<div class="field full"><label>${label}</label><textarea class="input textarea large-textarea editor-input" data-key="${key}">${item[key] || ''}</textarea></div>`; return `<div class="field ${type === 'full' ? 'full' : ''}"><label>${label}</label><input class="input editor-input" data-key="${key}" value="${val}"></div>`; }).join(''); const calcWrap = document.createElement('div'); calcWrap.className = 'field full calc-row'; const { calc, cause } = continentData(item.superficieConstruida, item.continenteSuma); calcWrap.innerHTML = `<div class="calc-card"><span>Contenido - causa</span><strong>${item.contenidoSuma ? 'A valor real' : 'NO CONSTA EN LA NOTA DEL PERITO'}</strong></div><div class="calc-card"><span>Continente calculado</span><strong>${money(calc)}</strong></div><div class="calc-card"><span>Continente - causa</span><strong>${cause}</strong></div>`; els.editorFields.appendChild(calcWrap); }
function fileSignature(file) { return [file.name, file.size, file.lastModified].join('::'); }
function mergeFiles(existing, incoming, max = 30) { const out = [...existing]; const seen = new Set(existing.map(fileSignature)); for (const file of incoming) { const sig = fileSignature(file); if (seen.has(sig)) continue; if (out.length >= max) break; seen.add(sig); out.push(file); } return out; }
function fileKindFromName(name='') { if (/\.(jpg|jpeg|png|webp|heic)$/i.test(name)) return 'image'; if (/\.pdf$/i.test(name)) return 'pdf'; return 'file'; }
function previewCardHtml(entry, { removable = false, removeAttr = '', index = 0, persisted = false } = {}) {
  const persistedEntry = entry.url && !entry.preview;
  const kind = entry.kind || fileKindFromName(entry.name || '');
  const preview = entry.preview || (kind === 'image' ? entry.url : '');
  const icon = kind === 'pdf' ? 'PDF' : 'ARCH';
  const removeBtn = removable ? `<button class="mini-delete" type="button" ${removeAttr}="${index}">Borrar</button>` : '';
  const status = persisted ? '<small class="muted">Guardado</small>' : '<small class="muted">Pendiente</small>';
  return `<div class="preview-card ${persisted ? 'persisted' : ''}">${kind === 'image' && preview ? `<img src="${preview}" alt="Archivo">` : `<div class="file-thumb">${icon}</div>`}<span>${entry.name || 'Archivo'}</span>${removeBtn}${status}</div>`;
}
function renderSelectedFiles(files, target, { allowRemove = false, removeAttr = 'data-remove', emptyText = 'Sin archivos seleccionados', persisted = [] } = {}) {
  const persistedHtml = persisted.map((f, i) => previewCardHtml(f, { removable: true, removeAttr: 'data-file-index', index: i, persisted: true })).join('');
  const pendingHtml = files.map((f, i) => previewCardHtml({ name: f.name, preview: f.type?.startsWith('image/') ? URL.createObjectURL(f) : '', kind: f.type?.startsWith('image/') ? 'image' : fileKindFromName(f.name) }, { removable: allowRemove, removeAttr, index: i, persisted: false })).join('');
  target.innerHTML = persistedHtml || pendingHtml ? `${persistedHtml}${pendingHtml}` : `<div class="empty-card small">${emptyText}</div>`;
}
function renderCreateFilePreview() { renderSelectedFiles(state.createFiles, els.photoPreview, { allowRemove: true, removeAttr: 'data-remove-create', emptyText: 'Sin archivos seleccionados' }); }
function renderEditorFileGallery(item = state.editorItem) { const archivos = item?.archivos || item?.fotos || []; renderSelectedFiles(state.editorQueuedFiles, els.editorPhotoPreview, { allowRemove: true, removeAttr: 'data-remove-editor-staged', emptyText: 'Sin archivos en el expediente', persisted: archivos }); const total = archivos.length + state.editorQueuedFiles.length; els.editorPhotoStatus.textContent = state.editorQueuedFiles.length ? `${state.editorQueuedFiles.length} archivos nuevos pendientes · total ${total}/30` : `Guardados ${archivos.length}/30`; }
function queueCreateFiles(fileList) { state.createFiles = mergeFiles(state.createFiles, [...fileList], 30); els.photoInput.value = ''; renderCreateFilePreview(); showToast(`Archivos preparados: ${state.createFiles.length}/30`); }
function queueEditorFiles(fileList) { const currentCount = (state.editorItem?.archivos || state.editorItem?.fotos || []).length + state.editorQueuedFiles.length; const room = Math.max(0, 30 - currentCount); state.editorQueuedFiles = mergeFiles(state.editorQueuedFiles, [...fileList].slice(0, room), room); els.editorPhotoInput.value = ''; renderEditorFileGallery(); if (room <= 0) showToast('Este expediente ya tiene 30 archivos'); else showToast(`Archivos en cola: ${state.editorQueuedFiles.length}`); }
function removeCreateFile(index) { state.createFiles.splice(index, 1); renderCreateFilePreview(); }
function removeEditorQueuedFile(index) { state.editorQueuedFiles.splice(index, 1); renderEditorFileGallery(); }
async function openEditor(id) { const item = await api(`/api/siniestros/${id}`); state.editorId = id; state.editorItem = item; state.editorQueuedFiles = []; els.editorTitle.textContent = `Siniestro ${item.numeroSiniestro || ''}`; if (item.audioUrl) els.editorAudio.src = item.audioUrl; else els.editorAudio.removeAttribute('src'); els.editorTranscript.value = item.transcript || ''; els.editorPhotoInput.value = ''; buildEditorFields(item); renderEditorFileGallery(item); els.editorDialog.showModal(); }
function collectEditorData() { const payload = { transcript: els.editorTranscript.value.trim(), archivos: state.editorItem?.archivos || state.editorItem?.fotos || [] }; document.querySelectorAll('.editor-input').forEach(input => payload[input.dataset.key] = input.value.trim()); return payload; }
async function uploadEditorFiles() { if (!state.editorId) return; if (!state.editorQueuedFiles.length) { showToast('No hay archivos nuevos pendientes'); return state.editorItem; } const fd = new FormData(); state.editorQueuedFiles.forEach(f => fd.append('archivos', f)); const item = await api(`/api/siniestros/${state.editorId}/files`, { method: 'POST', body: fd }); state.editorItem = item; state.editorQueuedFiles = []; els.editorPhotoInput.value = ''; renderEditorFileGallery(item); await loadCases(); showToast('Archivos guardados en el expediente'); return item; }
async function saveEditor() { if (state.editorQueuedFiles.length) await uploadEditorFiles(); const payload = collectEditorData(); const saved = await api(`/api/siniestros/${state.editorId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); state.editorItem = saved; showToast('Siniestro guardado'); await loadCases(); await openEditor(state.editorId); }
async function autoFillEditor() { if (state.editorQueuedFiles.length) await uploadEditorFiles(); await saveEditor(); const filled = await api(`/api/siniestros/${state.editorId}/autofill`, { method: 'POST' }); state.editorItem = filled; showToast('Campos rellenados con la transcripción'); await loadCases(); await openEditor(state.editorId); }
async function triggerBlobDownload(blob, filename) { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); }
async function downloadReport(id) { const blob = await api(`/api/siniestros/${id}/report`); await triggerBlobDownload(blob, `informe-${id}.html`); }
async function downloadFilesZip(id) { const blob = await api(`/api/siniestros/${id}/files-zip`); await triggerBlobDownload(blob, `archivos-${id}.zip`); }
async function updateState(id, nextState) { await api(`/api/siniestros/${id}/state`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ estado: nextState }) }); showToast(nextState === 'Hecho' ? 'Siniestro cerrado' : 'Siniestro reabierto'); await loadCases(); }
async function deleteCase(id) { if (!confirm('¿Seguro que quieres borrar este siniestro?')) return; await api(`/api/siniestros/${id}`, { method: 'DELETE' }); showToast('Siniestro borrado'); await loadCases(); }
async function clearClosed() { if (!confirm('¿Borrar todos los siniestros hechos?')) return; const data = await api('/api/siniestros-hechos', { method: 'DELETE' }); showToast(`Eliminados ${data.removed} siniestros hechos`); await loadCases(); }
async function createCase(ev) { ev.preventDefault(); const fd = new FormData(els.createForm); if (state.audioBlob) fd.append('audio', state.audioBlob, 'nota.webm'); state.createFiles.forEach(file => fd.append('archivos', file)); await api('/api/siniestros', { method: 'POST', body: fd }); showToast('Siniestro guardado'); els.createForm.reset(); els.audioPreview.classList.add('hidden'); els.audioPreview.removeAttribute('src'); state.audioBlob = null; state.createFiles = []; els.transcript.value = ''; renderCreateFilePreview(); updateCreateCalc(); switchView('pendientesView'); await loadCases(); }
async function startRecording() { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); state.chunks = []; state.mediaRecorder = new MediaRecorder(stream); state.mediaRecorder.ondataavailable = e => { if (e.data.size) state.chunks.push(e.data); }; state.mediaRecorder.onstop = () => { state.audioBlob = new Blob(state.chunks, { type: state.mediaRecorder.mimeType || 'audio/webm' }); els.audioPreview.src = URL.createObjectURL(state.audioBlob); els.audioPreview.classList.remove('hidden'); stream.getTracks().forEach(track => track.stop()); }; state.mediaRecorder.start(); els.recordingStatus.textContent = 'Grabando...'; els.startRecording.disabled = true; els.stopRecording.disabled = false; startSpeechRecognition(); } catch { showToast('No se pudo acceder al micrófono'); } }
function stopRecording() { if (state.mediaRecorder && state.mediaRecorder.state !== 'inactive') state.mediaRecorder.stop(); if (state.recognition) state.recognition.stop(); els.recordingStatus.textContent = 'Audio listo'; els.startRecording.disabled = false; els.stopRecording.disabled = true; }
function startSpeechRecognition() { const SR = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SR) { els.recordingStatus.textContent = 'Grabando... (sin transcripción automática en este navegador)'; return; } state.recognition = new SR(); state.recognition.lang = 'es-ES'; state.recognition.continuous = true; state.recognition.interimResults = true; const base = els.transcript.value.trim(); state.recognition.onresult = event => { let interim = ''; let final = base ? `${base} ` : ''; for (let i = 0; i < event.results.length; i++) { const t = event.results[i][0].transcript; if (event.results[i].isFinal) final += `${t} `; else interim += t; } els.transcript.value = `${final}${interim}`.trim(); }; state.recognition.start(); }
function wireNav() { document.querySelectorAll('.nav-btn').forEach(btn => btn.addEventListener('click', () => switchView(btn.dataset.viewTarget))); }
function wireListActions() { document.body.addEventListener('click', async ev => { const button = ev.target.closest('[data-action]'); if (!button) return; const { action, id, next } = button.dataset; try { if (action === 'open') await openEditor(id); if (action === 'report') await downloadReport(id); if (action === 'files') await downloadFilesZip(id); if (action === 'toggle') await updateState(id, next); if (action === 'delete') await deleteCase(id); } catch (err) { showToast(err.message); } }); }
async function deleteEditorFile(index) { if (!state.editorId) return; const item = await api(`/api/siniestros/${state.editorId}/files/${index}`, { method: 'DELETE' }); state.editorItem = item; renderEditorFileGallery(item); await loadCases(); showToast('Archivo borrado'); }
function bootstrap() {
  wireNav(); wireListActions();
  els.refreshBtn.addEventListener('click', loadCases); els.clearClosedBtn.addEventListener('click', clearClosed); els.searchInput.addEventListener('input', renderLists);
  els.createForm.addEventListener('submit', async ev => { try { await createCase(ev); } catch (err) { showToast(err.message); } });
  els.startRecording.addEventListener('click', startRecording); els.stopRecording.addEventListener('click', stopRecording);
  [els.surfaceInput, els.contentInput, els.continenteInput].forEach(el => el.addEventListener('input', updateCreateCalc));
  els.photoInput.addEventListener('change', () => queueCreateFiles(els.photoInput.files || []));
  els.photoPreview.addEventListener('click', ev => { const btn = ev.target.closest('[data-remove-create]'); if (!btn) return; removeCreateFile(Number(btn.dataset.removeCreate)); });
  els.closeEditor.addEventListener('click', () => els.editorDialog.close());
  els.saveEditorBtn.addEventListener('click', async () => { try { await saveEditor(); } catch (err) { showToast(err.message); } });
  els.autofillBtn.addEventListener('click', async () => { try { await autoFillEditor(); } catch (err) { showToast(err.message); } });
  els.downloadReportBtn.addEventListener('click', async () => { try { await downloadReport(state.editorId); } catch (err) { showToast(err.message); } });
  els.downloadPhotosBtn?.addEventListener('click', async () => { try { await downloadFilesZip(state.editorId); } catch (err) { showToast(err.message); } });
  els.editorPhotoInput.addEventListener('change', () => queueEditorFiles(els.editorPhotoInput.files || []));
  els.uploadEditorPhotosBtn?.addEventListener('click', async () => { try { await uploadEditorFiles(); } catch (err) { showToast(err.message); } });
  els.editorPhotoPreview.addEventListener('click', async ev => { const deletePersisted = ev.target.closest('[data-file-index]'); const deleteQueued = ev.target.closest('[data-remove-editor-staged]'); if (deleteQueued) return removeEditorQueuedFile(Number(deleteQueued.dataset.removeEditorStaged)); if (!deletePersisted) return; try { await deleteEditorFile(deletePersisted.dataset.fileIndex); } catch (err) { showToast(err.message); } });
}
(async function init() { bootstrap(); updateCreateCalc(); renderCreateFilePreview(); try { await loadOptions(); await loadCases(); } catch (err) { showToast(err.message); } })();
